// Dữ liệu 100 lá xin xăm — Check Vibe Vũ Trụ
// Cấu trúc: { so: 1-100, bac: tên bậc, vutru: luận giải, chill: bản dịch GenZ }
// Tỉ lệ: Thượng Thượng 25 · Thượng Kiết 30 · Thượng cẳng chân 25 · Cũng Cũng 12 · Hạ cẳng tay 8

var XAM_DATA = [
  { so: 1, bac: "Thượng Thượng", vutru: "Vận trình khai mở, trăm sự hanh thông, cầu gì được nấy.", chill: "Mở bài đẹp vậy là quá đã 🎉 Có ý tưởng gì thì tung liền, hôm nay vũ trụ bật đèn xanh hết cỡ!" },
  { so: 2, bac: "Thượng Thượng", vutru: "Quý nhân xuất hiện đúng lúc, việc khó cũng hóa dễ dàng.", chill: "Ai đó sắp giúp em 1 tay đó, để ý xung quanh nha, quý nhân đang ẩn danh gần đây thôi 👀" },
  { so: 3, bac: "Thượng Thượng", vutru: "Cầu tài như ý, công danh hanh thông, mọi sự đều thành.", chill: "Jackpot lá này! Deal gì đang chờ ký thì ký liền tay, hôm nay là ngày chốt đơn đúng nghĩa 💰" },
  { so: 4, bac: "Thượng Thượng", vutru: "Tâm nguyện thành tựu, ước mơ ấp ủ lâu ngày nay đơm hoa.", chill: "Cái mong ước để trong lòng lâu rồi á? Hôm nay nó rục rịch thành hiện thực đó nha 🌸" },
  { so: 5, bac: "Thượng Thượng", vutru: "Danh tiếng vang xa, được nhiều người biết đến và tán thưởng.", chill: "Nay có khi em lên xu hướng đó — cứ tự tin thể hiện, mọi người đang chú ý tới em rồi ✨" },
  { so: 6, bac: "Thượng Thượng", vutru: "Vạn sự khởi đầu thuận, về sau càng thêm rực rỡ.", chill: "Bắt đầu mượt là dấu hiệu cả chặng đường sẽ mượt luôn — cứ tiến lên phía trước thôi!" },
  { so: 7, bac: "Thượng Thượng", vutru: "Vận trình hanh thông, quý nhân phù trợ, mưu sự như ý, tài lộc song toàn.", chill: "Trời ơi lá này ngon nha 🎉 Việc gì đang ấp ủ thì tự tin triển liền đi, quý nhân chống lưng rồi đó!" },
  { so: 8, bac: "Thượng Thượng", vutru: "Gia đạo yên vui, người thân sum vầy, tâm an vạn sự an.", chill: "Về nhà là thấy chill liền á 🏡 Hôm nay dành thời gian cho người thân là đúng bài luôn!" },
  { so: 9, bac: "Thượng Thượng", vutru: "Sự nghiệp thăng tiến, nỗ lực bấy lâu được ghi nhận xứng đáng.", chill: "Bao công sức đổ ra cuối cùng có người thấy rồi 🙌 Cứ tự hào về bản thân đi, xứng đáng mà!" },
  { so: 10, bac: "Thượng Thượng", vutru: "Xuất hành đại lợi, đi đến đâu cũng gặp may mắn theo cùng.", chill: "Đi đâu hôm nay cũng auto hên á 🍀 Có kèo rủ đi chơi/đi công tác thì OK liền không cần suy nghĩ!" },
  { so: 11, bac: "Thượng Thượng", vutru: "Tình duyên viên mãn, hai bên tâm đầu ý hợp, hạnh phúc bền lâu.", chill: "Couple energy đang max power đó nha 💕 Độc thân thì hôm nay dễ gặp người hợp gu lắm!" },
  { so: 12, bac: "Thượng Thượng", vutru: "Trí tuệ minh mẫn, quyết định đưa ra đều sáng suốt, đúng đắn.", chill: "Não hôm nay hoạt động ở chế độ 200% á 🧠 Quyết định gì khó thì hôm nay làm luôn, chuẩn không cần chỉnh!" },
  { so: 13, bac: "Thượng Thượng", vutru: "Sức khỏe dồi dào, tinh thần phấn chấn, năng lượng tràn đầy.", chill: "Full pin cả ngày luôn á 🔋 Việc gì cần sức thì làm hôm nay, mai tính sau!" },
  { so: 14, bac: "Thượng Thượng", vutru: "Được người trên tin tưởng, giao phó trọng trách quan trọng.", chill: "Sếp/thầy cô đang để mắt tới em đó — cơ hội thể hiện đang tới, đừng bỏ lỡ nha!" },
  { so: 15, bac: "Thượng cẳng chân", vutru: "Việc chưa thấy rõ hướng, nên bình tĩnh quan sát thêm trước khi hành động.", chill: "Chưa phải lúc bấm nút go đâu — kiểu vũ trụ đang bảo để tao xem đã, cứ chill thêm chút nha!" },
  { so: 16, bac: "Thượng Thượng", vutru: "Học hành tấn tới, thi cử thuận lợi, kiến thức tích lũy phát huy đúng lúc.", chill: "Ôn bài bao lâu nay cuối cùng cũng vào đúng đề rồi 📚 Tự tin làm bài thôi!" },
  { so: 17, bac: "Thượng Thượng", vutru: "Việc lớn có trở ngại nhỏ ban đầu, nhưng về sau thuận lợi, kiên trì ắt thành.", chill: "Đầu hơi chông gai xíu nhưng đừng lo, khó lúc đầu dễ lúc sau — ráng qua vài bữa đầu là mượt liền!" },
  { so: 18, bac: "Thượng Kiết", vutru: "Người xa mang tin vui đến, việc mong đợi lâu nay sắp có kết quả.", chill: "Có tin nhắn/cuộc gọi bất ngờ từ ai đó xa xa sắp tới đó, mà toàn tin vui thôi nha 📱" },
  { so: 19, bac: "Thượng Thượng", vutru: "Hợp tác thuận lợi, đối tác chân thành, công việc chung suôn sẻ.", chill: "Làm nhóm hôm nay dễ thở lắm, đồng đội hiểu ý nhau, không cần cãi nhau nhiều 🤝" },
  { so: 20, bac: "Thượng Kiết", vutru: "Tiền tài từ xa mang lại, cơ hội bất ngờ đem đến lợi ích.", chill: "Có khi hôm nay lụm được deal ngon từ đâu đó không ngờ tới đó 🎁 Để ý cơ hội xung quanh!" },
  { so: 21, bac: "Thượng Kiết", vutru: "Bệnh tật tiêu tan, sức khỏe dần hồi phục, tinh thần lạc quan trở lại.", chill: "Cảm giác nặng nề mấy bữa nay sắp tan biến rồi á, nhẹ nhõm hơn liền cho coi!" },
  { so: 22, bac: "Thượng Kiết", vutru: "Kiện tụng tranh chấp dần được hóa giải, đôi bên tìm được tiếng nói chung.", chill: "Drama gần đây đang có dấu hiệu hạ nhiệt rồi đó, cứ bình tĩnh là mọi thứ ổn thôi!" },
  { so: 23, bac: "Thượng Kiết", vutru: "Việc lớn có trở ngại nhỏ ban đầu, nhưng về sau thuận lợi, kiên trì ắt thành.", chill: "Đầu hơi chông gai xíu nhưng đừng lo, khó lúc đầu dễ lúc sau — ráng qua vài bữa đầu là mượt liền, đừng bỏ cuộc giữa chừng uổng lắm!" },
  { so: 24, bac: "Thượng cẳng chân", vutru: "Cầu tài chưa vượng, nên giữ vững tinh thần, đừng nản chí.", chill: "Ví hôm nay hơi mỏng chút xíu, không sao đâu, giữ vibe tích cực là tự khắc nó đầy lại thôi!" },
  { so: 25, bac: "Thượng Thượng", vutru: "Xuất hành có quý nhân đồng hành, chuyến đi an toàn thuận lợi.", chill: "Đi đâu hôm nay cũng có người ngầm bảo vệ á, cứ yên tâm lên đường!" },
  { so: 26, bac: "Thượng cẳng chân", vutru: "Tình cảm còn nhiều điều chưa rõ, cần thời gian để thấu hiểu nhau hơn.", chill: "Chuyện tình cảm đang ở giai đoạn tìm hiểu, đừng vội kết luận gì cả, cứ để tự nhiên diễn ra!" },
  { so: 27, bac: "Thượng Thượng", vutru: "Danh tiếng dần lan tỏa, công sức bỏ ra được người khác công nhận.", chill: "Từ từ mà chắc, tiếng lành đồn xa á, cứ làm tốt việc của mình là tự nhiên người ta biết tới!" },
  { so: 28, bac: "Thượng Kiết", vutru: "Gia đạo có tin vui nhỏ, không khí gia đình thêm phần ấm áp.", chill: "Nhà cửa hôm nay có gì đó vui vui đó, để ý mà tận hưởng khoảnh khắc nha!" },
  { so: 29, bac: "Thượng cẳng chân", vutru: "Sự nghiệp bình ổn, chưa có đột phá lớn, cần tích lũy thêm.", chill: "Công việc đang kiểu ổn định, chưa bùng nổ liền được đâu — cứ tích luỹ, sẽ tới lúc thôi!" },
  { so: 30, bac: "Thượng Kiết", vutru: "Học hành có người chỉ dạy tận tâm, tiếp thu kiến thức dễ dàng hơn.", chill: "Có ai đó sẽ giảng bài dễ hiểu hơn cho em hôm nay đó, đừng ngại hỏi nha!" },
  { so: 31, bac: "Thượng Kiết", vutru: "Sức khỏe cải thiện dần, chỉ cần thêm chút kiên nhẫn nghỉ ngơi.", chill: "Cơ thể đang hồi phục từ từ, đừng ép bản thân quá, nghỉ thêm chút là ổn hẳn luôn!" },
  { so: 32, bac: "Thượng cẳng chân", vutru: "Kiện tụng tranh chấp nên tránh, hòa giải là thượng sách lúc này.", chill: "Có drama gì thì hôm nay né bớt đi, làm hoà vẫn ngon hơn là cãi tay đôi!" },
  { so: 33, bac: "Thượng Thượng", vutru: "Người quen cũ mang lại tin tốt, mối quan hệ xưa được nối lại.", chill: "Bạn cũ nào đó sắp liên lạc lại với tin vui đó, để ý điện thoại nha!" },
  { so: 34, bac: "Thượng cẳng chân", vutru: "Việc mưu cầu cần thêm thời gian, chưa nên vội vàng thúc ép.", chill: "Đừng thúc deadline sớm quá, để mọi thứ chín muồi tự nhiên sẽ ngon hơn nhiều!" },
  { so: 35, bac: "Thượng cẳng chân", vutru: "Được mất đan xen, giữ tâm bình thản thì sự việc tự nhiên hanh thông.", chill: "Nay kiểu nửa ly nước đầy — có cái được có cái chưa, bình thường thôi, đừng để 1 chuyện nhỏ làm sập mood cả ngày!" },
  { so: 36, bac: "Thượng Kiết", vutru: "Tài lộc từ công sức bản thân, làm bao nhiêu hưởng bấy nhiêu xứng đáng.", chill: "Công sức bỏ ra hôm nay chắc chắn không phí đâu, cứ chăm chỉ là có quả ngọt liền!" },
  { so: 37, bac: "Thượng cẳng chân", vutru: "Việc riêng tư nên giữ kín, chưa phải lúc thích hợp để công khai.", chill: "Có chuyện gì đó thì giữ bí mật thêm xíu nha, chưa phải lúc show ra đâu!" },
  { so: 38, bac: "Thượng Thượng", vutru: "Cơ hội mới xuất hiện, nắm bắt đúng lúc sẽ có lợi lớn.", chill: "Cơ hội đang lượn lờ gần đây đó, tỉnh táo nhận ra là chớp lấy liền nha!" },
  { so: 39, bac: "Thượng cẳng chân", vutru: "Xuất hành nên cẩn trọng, không nên vội vã, chọn thời điểm thích hợp.", chill: "Trước khi quẹo xe đổi hướng cuộc đời thì check kỹ Google Maps chút — đi chậm 1 nhịp cho chắc ăn!" },
  { so: 40, bac: "Thượng Thượng", vutru: "Tình cảm dần ổn định, hai bên thấu hiểu nhau hơn theo thời gian.", chill: "Mối quan hệ đang đi đúng hướng, cứ để thời gian làm phần việc của nó!" },
  { so: 41, bac: "Thượng Kiết", vutru: "Tình duyên tốt đẹp, người thân hòa hợp, việc cầu hôn nhân thuận lợi.", chill: "Tim đập nhanh chưa? Ai đang thầm thương trộm nhớ thì bật đèn xanh đi, lá này báo đúng người đúng thời điểm đó!" },
  { so: 42, bac: "Thượng cẳng chân", vutru: "Danh tiếng chưa vang xa, cần thêm thời gian để người khác nhận ra giá trị.", chill: "Người ta chưa thấy hết được giá trị của em đâu, nhưng không sao, thời gian sẽ chứng minh!" },
  { so: 43, bac: "Thượng Kiết", vutru: "Gia đạo êm ấm, mọi thành viên đều mạnh khỏe, an vui.", chill: "Cả nhà đều ổn cả, đây chính là hạnh phúc giản đơn nhất rồi đó, trân trọng nha!" },
  { so: 44, bac: "Thượng cẳng chân", vutru: "Sự nghiệp cần thêm nỗ lực, đừng chỉ dựa vào may mắn nhất thời.", chill: "May mắn có thể giúp 1 phần thôi, phần còn lại vẫn cần em cày thêm nha, cố lên!" },
  { so: 45, bac: "Thượng Thượng", vutru: "Học hành đạt kết quả tốt, công sức bỏ ra được đền đáp xứng đáng.", chill: "Ôn bài cực khổ mấy bữa nay sắp có kết quả xứng đáng rồi đó, ráng nốt chút thôi!" },
  { so: 46, bac: "Cũng Cũng", vutru: "Mưu sự trắc trở, cần nhẫn nại, chớ nóng vội mà hỏng việc lớn.", chill: "Hôm nay hơi lag 1 chút, nhưng lag không có nghĩa là crash — nghỉ tay uống ngụm nước, quay lại làm tiếp là ổn!" },
  { so: 47, bac: "Thượng Kiết", vutru: "Sức khỏe ổn định, tinh thần minh mẫn, thích hợp để lên kế hoạch mới.", chill: "Đầu óc đang tỉnh táo phết, hôm nay hợp để ngồi vẽ ra plan mới cho bản thân đó!" },
  { so: 48, bac: "Thượng cẳng chân", vutru: "Việc chưa rõ ràng, cần thêm thông tin trước khi đưa ra quyết định.", chill: "Chưa đủ dữ kiện để quyết đâu, tìm hiểu thêm chút xíu nữa rồi hẵng chốt nha!" },
  { so: 49, bac: "Thượng Kiết", vutru: "Được người khác giúp đỡ đúng lúc, việc khó hóa thành dễ dàng.", chill: "Có ai đó sẽ xuất hiện đúng lúc em cần nhất đó, cứ mở lòng nhờ vả khi cần nha!" },
  { so: 50, bac: "Thượng cẳng chân", vutru: "Tài lộc bình thường, không nên đầu tư mạo hiểm lúc này.", chill: "Tiền bạc hôm nay giữ ở mức an toàn thôi, đừng liều lĩnh xuống tiền lớn nha!" },
  { so: 51, bac: "Thượng Thượng", vutru: "Tin vui từ phương xa, người thân bạn bè mang đến tín hiệu tốt lành.", chill: "Có tin nhắn gì đó đáng mong chờ đang trên đường tới em rồi đó, kiên nhẫn chút!" },
  { so: 52, bac: "Thượng cẳng chân", vutru: "Xuất hành nên cẩn trọng, không nên vội vã, chọn thời điểm thích hợp.", chill: "Trước khi quyết đi đâu xa thì cân nhắc kỹ chút, đi chậm 1 nhịp cho chắc ăn thôi!" },
  { so: 53, bac: "Cũng Cũng", vutru: "Việc mưu cầu chưa thấy kết quả rõ ràng, cần thêm thời gian chờ đợi.", chill: "Chưa thấy quả đâu nhưng cây vẫn đang lớn ngầm đó, kiên nhẫn thêm chút thôi bồ!" },
  { so: 54, bac: "Thượng Kiết", vutru: "Tình cảm được vun đắp bền chặt hơn qua những khó khăn đã trải qua.", chill: "Sóng gió mấy bữa nay hoá ra lại làm tình cảm khắng khít hơn đó, coi như bài test thành công!" },
  { so: 55, bac: "Thượng cẳng chân", vutru: "Công việc cần thêm sự kiên nhẫn, kết quả sẽ đến chậm nhưng chắc.", chill: "Chưa thấy kết quả liền đâu nhưng không có nghĩa là không có, cứ đều đặn là ổn!" },
  { so: 56, bac: "Thượng Kiết", vutru: "Học hành tiến bộ rõ rệt, sự cố gắng được thầy cô ghi nhận.", chill: "Cố gắng mấy bữa nay có người để ý tới rồi đó, tự hào bản thân đi nha!" },
  { so: 57, bac: "Cũng Cũng", vutru: "Sức khỏe bình thường, nên chú ý nghỉ ngơi điều độ hơn.", chill: "Cơ thể đang nhắc khéo em ngủ sớm hơn đó, nghe lời nó đi, đừng thức khuya nữa!" },
  { so: 58, bac: "Thượng Kiết", vutru: "Học hành thi cử thuận lợi, trí tuệ minh mẫn, được người giúp đỡ.", chill: "Não hôm nay đang chạy full tốc độ, học gì vô nấy — deadline nào khó nhằn thì hôm nay táng cho xong!" },
  { so: 59, bac: "Thượng cẳng chân", vutru: "Gia đạo bình yên, không có biến động lớn, giữ hiện trạng là tốt.", chill: "Mọi thứ đang ổn, không cần thay đổi gì to tát đâu, cứ duy trì vậy là ngon rồi!" },
  { so: 60, bac: "Thượng Thượng", vutru: "Cầu tài có quý nhân giúp sức, việc kiếm tiền thuận lợi hơn thường lệ.", chill: "Có người ngầm giúp em kiếm tiền dễ hơn hôm nay đó, để ý cơ hội hợp tác nha!" },
  { so: 61, bac: "Thượng cẳng chân", vutru: "Tình cảm chưa có tiến triển rõ, cần thêm sự chủ động từ cả hai phía.", chill: "Chuyện tình cảm đang dậm chân tại chỗ á, ai đó cần chủ động 1 bước thì mới nhích được!" },
  { so: 62, bac: "Thượng Kiết", vutru: "Sự nghiệp có bước tiến nhỏ nhưng chắc chắn, nền tảng vững hơn trước.", chill: "Từng bước nhỏ cũng là bước tiến mà, không cần nhảy vọt, chắc chắn là được rồi!" },
  { so: 63, bac: "Thượng cẳng chân", vutru: "Xuất hành bình thường, không có gì đặc biệt cần lưu ý.", chill: "Hôm nay đi đâu cũng bình thường thôi, không hên không xui, cứ đi như mọi khi nha!" },
  { so: 64, bac: "Cũng Cũng", vutru: "Việc riêng tư gặp chút vướng mắc, cần thời gian để tháo gỡ dần.", chill: "Có chuyện riêng hơi rối 1 chút, đừng cố gỡ hết trong 1 ngày, từ từ tháo từng nút thôi!" },
  { so: 65, bac: "Thượng Kiết", vutru: "Danh tiếng được củng cố, uy tín trong mắt người khác tăng lên.", chill: "Uy tín của em đang lên đó, mọi người tin tưởng hơn rồi, giữ vững phong độ nha!" },
  { so: 66, bac: "Cũng Cũng", vutru: "Mưu sự trắc trở, cần nhẫn nại, chớ nóng vội mà hỏng việc lớn.", chill: "Hôm nay hơi lag 1 chút, nhưng lag không có nghĩa là crash — nghỉ tay uống ngụm nước, quay lại làm tiếp là ổn, đừng đập bàn phím nha 😤➡️😌" },
  { so: 67, bac: "Thượng Kiết", vutru: "Được cấp trên tin tưởng, cơ hội thể hiện năng lực sắp đến gần.", chill: "Sếp đang để mắt tới em đó, cơ hội show năng lực sắp tới rồi, chuẩn bị sẵn sàng nha!" },
  { so: 68, bac: "Thượng cẳng chân", vutru: "Tài lộc bình ổn, không có biến động lớn, giữ vững chi tiêu hợp lý.", chill: "Tiền bạc hôm nay ổn định, không cần lo lắng gì, cứ chi tiêu hợp lý là được!" },
  { so: 69, bac: "Cũng Cũng", vutru: "Sức khỏe cần chú ý hơn, nên nghỉ ngơi thay vì cố gắng quá sức.", chill: "Cơ thể đang xin nghỉ phép đó, đừng ép nó làm việc quá sức hôm nay nha!" },
  { so: 70, bac: "Thượng Kiết", vutru: "Học hành có bước tiến, kiến thức tích lũy dần được củng cố vững chắc.", chill: "Kiến thức đang ngấm dần vô đầu rồi đó, cứ kiên trì học là chắc chắn nhớ lâu!" },
  { so: 71, bac: "Thượng cẳng chân", vutru: "Gia đạo cần thêm sự quan tâm, dành thời gian cho người thân nhiều hơn.", chill: "Lâu rồi chưa hỏi thăm gia đình thì hôm nay nhắn tin hỏi thăm 1 câu đi, ấm lòng lắm đó!" },
  { so: 72, bac: "Thượng Kiết", vutru: "Cầu tài có kết quả nhỏ nhưng ổn định, tích lũy dần sẽ thành lớn.", chill: "Kiếm được ít cũng là kiếm được, tích tiểu thành đại mà, đừng chê nhỏ nha!" },
  { so: 73, bac: "Cũng Cũng", vutru: "Việc mưu cầu cần xem xét lại hướng đi, có thể chưa đúng cách tiếp cận.", chill: "Cách làm hiện tại hình như chưa work lắm, thử đổi hướng khác coi sao nha!" },
  { so: 74, bac: "Thượng Kiết", vutru: "Tình cảm được người xung quanh ủng hộ, thuận lợi hơn nhờ sự trợ giúp.", chill: "Bạn bè xung quanh đang cổ vũ chuyện tình cảm của em đó, cứ tự tin tiến tới!" },
  { so: 75, bac: "Thượng cẳng chân", vutru: "Sự nghiệp giữ mức ổn định, chưa cần thay đổi lớn trong giai đoạn này.", chill: "Công việc đang ổn, chưa cần nhảy việc hay đổi hướng gì đâu, cứ giữ vậy đã!" },
  { so: 76, bac: "Thượng Kiết", vutru: "Xuất hành gặp nhiều điều thú vị, chuyến đi mang lại trải nghiệm đáng nhớ.", chill: "Đi đâu hôm nay cũng có chuyện hay ho để kể lại đó, cứ xách balo lên thôi!" },
  { so: 77, bac: "Cũng Cũng", vutru: "Kiện tụng tranh chấp chưa ngã ngũ, cần thêm thời gian để giải quyết.", chill: "Chuyện tranh cãi chưa xong đâu, đừng nóng vội, để thêm chút thời gian là rõ ràng hơn!" },
  { so: 78, bac: "Thượng Kiết", vutru: "Được người thân trợ giúp lúc khó khăn, tình cảm gia đình thêm khắng khít.", chill: "Gia đình sẽ là chỗ dựa vững chắc cho em lúc này đó, đừng ngại nhờ vả nha!" },
  { so: 79, bac: "Cũng Cũng", vutru: "Tài lộc chưa vượng, nên tiết chế chi tiêu, tích luỹ chờ thời.", chill: "Ví tiền hôm nay hơi eo hẹp xíu, kiểu vũ trụ nhắc khéo để dành đi cưng — trà sữa mai uống cũng được!" },
  { so: 80, bac: "Thượng Kiết", vutru: "Sức khỏe cải thiện nhờ tinh thần lạc quan, tâm an thì thân cũng an.", chill: "Giữ mood vui vẻ là cách chữa lành tốt nhất hôm nay đó, cứ cười nhiều lên nha!" },
  { so: 81, bac: "Thượng cẳng chân", vutru: "Học hành cần thêm sự tập trung, tránh xao nhãng bởi việc khác.", chill: "Hôm nay não hơi lo ra xíu, tắt bớt thông báo điện thoại đi để tập trung học nha!" },
  { so: 82, bac: "Thượng Kiết", vutru: "Gia đạo có tin vui, không khí gia đình thêm phần rộn ràng.", chill: "Nhà cửa hôm nay có tin gì đó vui vui á, đón nhận với tâm thế thoải mái nha!" },
  { so: 83, bac: "Thượng cẳng chân", vutru: "Việc riêng tư cần cẩn trọng lời ăn tiếng nói, tránh hiểu lầm không đáng có.", chill: "Nói chuyện hôm nay uốn lưỡi 7 lần trước khi phát ngôn nha, dễ bị hiểu lầm lắm!" },
  { so: 84, bac: "Thượng Kiết", vutru: "Cơ hội hợp tác mới xuất hiện, mang lại lợi ích cho cả đôi bên.", chill: "Có kèo hợp tác win-win đang tới đó, cân nhắc kỹ rồi gật đầu nha!" },
  { so: 85, bac: "Thượng cẳng chân", vutru: "Tình duyên chưa rõ ràng, cần thời gian để hai bên hiểu nhau hơn.", chill: "Chuyện tình cảm đang mơ hồ á, đừng vội đặt tên cho mối quan hệ, cứ để tự nhiên!" },
  { so: 86, bac: "Thượng Kiết", vutru: "Danh tiếng lan rộng nhờ sự chân thành trong công việc và cư xử.", chill: "Sống thật với chính mình đang giúp em ghi điểm với nhiều người đó, cứ là chính mình thôi!" },
  { so: 87, bac: "Cũng Cũng", vutru: "Sự nghiệp có chút trì trệ, cần kiên nhẫn chờ thời cơ thích hợp hơn.", chill: "Công việc đang hơi đứng yên xíu, không sao, dưỡng sức chờ thời cơ bung nóc tiếp!" },
  { so: 88, bac: "Thượng Kiết", vutru: "Xuất hành thuận lợi, gặp được người tốt giúp đỡ trên đường đi.", chill: "Đi đâu hôm nay cũng dễ gặp người tốt bụng giúp đỡ đó, cứ yên tâm lên đường!" },
  { so: 89, bac: "Thượng cẳng chân", vutru: "Cầu tài cần thêm kiên nhẫn, chưa phải lúc thu hoạch thành quả.", chill: "Tiền bạc chưa vô liền đâu, nhưng hạt giống đang nảy mầm rồi, chờ thêm chút xíu nha!" },
  { so: 90, bac: "Thượng Kiết", vutru: "Học hành có người đồng hành, việc tiếp thu kiến thức trở nên nhẹ nhàng hơn.", chill: "Học nhóm hôm nay là lựa chọn hay đó, có bạn đồng hành sẽ dễ vào bài hơn nhiều!" },
  { so: 91, bac: "Hạ cẳng tay", vutru: "Giai đoạn nên lùi lại quan sát, không phải lúc bứt tốc mà là lúc chuẩn bị kỹ.", chill: "Nay không phải ngày để flex đâu bạn ơi — kiểu main character nghỉ 1 tập, để nhân vật phụ toả sáng, mình dưỡng sức chờ tập sau bùng nổ tiếp 🎬" },
  { so: 92, bac: "Hạ cẳng tay", vutru: "Việc mưu cầu chưa thuận, nên tạm gác lại, chờ thời điểm tốt hơn.", chill: "Việc này để đó tính sau đi, hôm nay không hợp lắm đâu, làm chuyện khác cho nhẹ đầu!" },
  { so: 93, bac: "Hạ cẳng tay", vutru: "Sức khỏe cần được quan tâm nhiều hơn, tránh làm việc quá sức.", chill: "Cơ thể đang gửi tín hiệu SOS nhẹ đó, nghỉ ngơi sớm đi, đừng cố gồng nha!" },
  { so: 94, bac: "Cũng Cũng", vutru: "Tình cảm có chút hiểu lầm nhỏ, cần bình tĩnh trao đổi để rõ ràng hơn.", chill: "Có gì khó chịu trong lòng thì nói ra luôn đi, im lặng dễ thành hiểu lầm to lắm!" },
  { so: 95, bac: "Hạ cẳng tay", vutru: "Việc đang làm cần xem xét lại từ gốc, đổi cách tiếp cận sẽ thấy lối ra.", chill: "Cách cũ không work thì đổi cách khác thử coi — không phải bạn dở, chỉ là công thức chưa đúng thôi!" },
  { so: 96, bac: "Cũng Cũng", vutru: "Tài lộc chưa thuận, nên thận trọng trong các quyết định liên quan tiền bạc.", chill: "Hôm nay không phải ngày để xuống tiền lớn đâu, cân nhắc kỹ trước khi quẹt thẻ nha!" },
  { so: 97, bac: "Hạ cẳng tay", vutru: "Xuất hành nên hoãn lại nếu không thật cần thiết, ở nhà an toàn hơn.", chill: "Không có việc gấp thì hôm nay ở nhà cày phim, ra ngoài dễ gặp xui lặt vặt lắm!" },
  { so: 98, bac: "Hạ cẳng tay", vutru: "Gia đạo có chút xáo trộn nhỏ, cần bình tĩnh xử lý để mọi việc êm xuôi.", chill: "Nhà cửa hôm nay hơi lộn xộn 1 tí, giữ bình tĩnh xử lý từng việc là ổn ngay!" },
  { so: 99, bac: "Hạ cẳng tay", vutru: "Sự nghiệp gặp thử thách, cần thêm thời gian và sự kiên trì để vượt qua.", chill: "Bài test khó hôm nay á, nhưng qua được là lên trình liền — cố lên, sắp xong rồi!" },
  { so: 100, bac: "Hạ cẳng tay", vutru: "Việc đang làm cần xem xét lại từ gốc, đổi cách tiếp cận sẽ thấy lối ra.", chill: "Cách cũ không work thì đổi cách khác thử coi — không phải bạn dở, chỉ là công thức chưa đúng thôi, debug lại là chạy ngon liền!" }
];
